### ISSUE TITLE
Convert CSV to OpenReferral data

### ISSUE THREAD

**Issue by aramonc** [Code-for-Miami/Miami-Open-211#3]
The CSV in this repo contains data from the Switchboard of Miami. It needs to be converted to the OpenReferral specification: [Github repo here](http://github.com/codeforamerica/OpenReferral) — [Updated spec documentation here](https://docs.google.com/document/d/1gmNS4pBvkX4cI2wtH3Qco3uGF4LLTq1OJ0Pb_CLuxlk/edit)

1. Fields from the CSV need to be mapped to OpenReferral
2. A script needs to be created to convert the mapped fields into OpenReferral CSVs

**Comment by greggish** [comment]
FYI, updated Open Referral spec here: https://github.com/codeforamerica/OpenReferral ~ 
An example datapackage here: https://github.com/codeforamerica/OpenReferral/blob/master/datapackage.json

**Comment by ralphreid** [comment]
Hi @aramonc - do you still need help on this?

**Comment by eddroid** [comment]
@ralphreid This is mostly done. Mapping proposal defined at https://github.com/eddroid/Miami-Open-211/blob/master/mapping.csv. Unmapped fields documented and moved to https://github.com/Code-for-Miami/ohana-api/issues/2

**Comment by ErnieAtLYD** [comment]
Should we marked this closed then?

**Comment by eddroid** [comment]
Yes. In fact this whole repo would be unnecessary if not for [this ~~jerk~~ CodeForAmerica volunteer](https://github.com/eddroid/ohana-api/commit/c05164ac95e0c002c8df60bde796209130b5d7fc). Otherwise we could keep the data and the app that uses it together in one place.

**Comment by ErnieAtLYD** [comment]
Okay - closing the issue per conversation. Thanks, @eddroid!
